name: 'retailco_dbt'
version: '1.0.0'
config-version: 2

profile: 'retailco'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  retailco_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
